jwt.secret=myfancysecret
server.port=8083

spring.application.name=users-api
spring.zipkin.baseUrl=${ZIPKIN_URL:http://127.0.0.1:9411/}
spring.sleuth.sampler.percentage=100.0
spring.redis.host=redis
spring.redis.port=6379


# H2 Configuration
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update