apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
  namespace: microservices
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  ports:
  - port: 9200
    targetPort: 9200
    protocol: TCP
  type: ClusterIP
