apiVersion: v1
kind: Service
metadata:
  name: users-api-service
  namespace: microservices
  labels:
    app: users-api
spec:
  selector:
    app: users-api
  ports:
  - port: 8083
    targetPort: 8083
    protocol: TCP
  type: ClusterIP
